name: Build image
on:
  push:
    branches:
      - 'master'
jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build -t ghcr.io/pnagibin/webserver:latest .
          echo ${{secrets.CR_PAT}} | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/pnagibin/webserver:latest