name: Build image
on:
  push:
    tags: 
       - v1.**
jobs:
  install-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          apt-cache policy docker-ce
          sudo apt install docker-ce
          sudo systemctl status docker
          sudo usermod -aG docker ${USER}
  build-and-publish-image:
    needs: [install-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build -t ghcr.io/pnagibin/webserver:v1.0.0 -t ghcr.io/pnagibin/webserver:latest .
          echo ${{secrets.CR_PAT}} | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/pnagibin/webserver --all-tags
  deploy-in-kubernetes:
    needs: [build-and-publish-image]
    runs-on: self-hosted
    steps:
      - name: deploy-in-kubernetes
        run: ansible-playbook -i /home/nagibin/ansible/hosts.cfg -u nagibin /home/nagibin/ansible/kube-redeployment.yaml -v



