name: Deploy image
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  add-release-tag-to-image:
    runs-on: ubuntu-latest
    steps:
      - name: add-release-tag-to-image
        run: |
          echo ${{secrets.CR_PAT}} | docker login ghcr.io -u USERNAME --password-stdin
          docker image pull ghcr.io/pnagibin/webserver
          echo ${{ github.ref_name }}
          docker tag ghcr.io/pnagibin/webserver:latest ghcr.io/pnagibin/webserver:${{ github.ref_name }}
          docker push ghcr.io/pnagibin/webserver --all-tags
  deploy-in-kubernetes:
    needs: add-release-tag-to-image
    runs-on: self-hosted
    steps:
      - name: deploy-in-kubernetes
        run: |
          ansible-playbook -i /home/nagibin/ansible/hosts.cfg -u nagibin /home/nagibin/ansible/kube-redeployment.yaml --extra-vars "${{ github.ref_name }}"  -v